### ISSUE TITLE
Sign in failed

### ISSUE THREAD

**Issue by mthnzbk** [cgisca/PGSGP#38]
When I try to login to google play service, I get error code 4.

**Comment by cgisca** [comment]
Hello @mthnzbk , 
please follow instructions for setting up Google Play Games services from the [Get started](https://developers.google.com/games/services/android/quickstart#step_2_set_up_the_game_in_the_dev_console) page. 
This error code is due to bad configuration. Check SHA1 key that you entered when configured Google Play services. Following [link](https://developers.google.com/games/services/console/enabling#c_specify_client_id_settings) also can be helpful.

**Comment by mthnzbk** [comment]
I was able to log in in my previous attempts, but this problem started even though I did not change anything. i will try again anyway.

**Comment by mthnzbk** [comment]
It is mentioned in the res / values / ids.xml file but I don't understand what to do. I was also able to log in and register on the leaderboard on the devices I tested before. I produce new apk without making any changes.

**Comment by BilawalSarwar** [comment]
I had the same problem then i enable Google Drive API from Google API Console.

**Comment by mthnzbk** [comment]
@BilawalSarwar drive api is enabled. I also do not save games.

**Comment by himaghnam** [comment]
You also need sha1 of playstore (converted) if you are publishing so that makes 3 debug - release - playstore

**Comment by mthnzbk** [comment]
@gamergamesz When you install the release version as apk, it becomes signin. However, it doesn't happen when you install it from the store.

**Comment by himaghnam** [comment]
Yes because playstore change your sha1 key / your keystore

**Comment by mthnzbk** [comment]
omg. Thank you. it irritates you when you don't know: D
