### ISSUE TITLE
Google Drive API ?

### ISSUE THREAD

**Issue by anisc** [cgisca/PGSGP#8]
Why ?

**Comment by cgisca** [comment]
The snapshots API relies on the Google Drive API for saved games storage.
You can find more info here https://developers.google.com/games/services/android/savedgames

**Comment by cgeadas** [comment]
Using Google Drive requires and additional permission from users. I would like to avoid this, since I just want to provide score and achievements and most games don't use google drive. Is it possible you can make a "lights" version of your module that doesn't include the saved game components so, not requiring additional permissions?
I don't know java, so I don't know what to cut :-)

**Comment by cgisca** [comment]
@cgeadas I will try to update the library in order to specify if you want to use saved games, if not permission will not be requested.

**Comment by cgisca** [comment]
@cgeadas please check out latest plugin 1.2.0 (https://github.com/cgisca/PGSGP/releases/tag/1.2.0) . Now you are able to enable/disable Saved Games functionality. Please read carefully ReadMe file, it updated a bit.

**Comment by cgeadas** [comment]
@cgisca thank you for the update. I'll try it next week when I start programming my next game.
